name: auto_attend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image:
  http:
  wifi_scan: ^0.4.1+1
  flutter_face_api: ^6.3.591
  image_picker: ^1.1.2
  sqflite: ^2.4.0
  path: ^1.9.0
  path_provider: ^2.1.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  loading_animation_widget:
  

flutter:
  uses-material-design: true
