DELETE FROM attendance;
DELETE FROM student_enrollments;
DELETE FROM teacher_assignments;
DELETE FROM classes;
DELETE FROM students;
DELETE FROM teachers;
DELETE FROM subjects;
DELETE FROM departments;
DELETE FROM user_accounts;
